### ISSUE TITLE
Clean-up / organize codegen tests

### ISSUE THREAD

**Issue by epau** [smithy-lang/smithy-swift#469]
Currently, when generating code for tests such as verifying the Codable conformance for some model is as expected, the code generation logic for tests is different than that which is used for production. This can result in issues slipping as tests can provide false positives. 

To alleviate this, let's audit the code gen flow for production and ensure all tests go through the same flow (as much as possible). 

The following is a concrete example of this issue. 

In production, some preprocessing is done on the models [here](https://github.com/awslabs/smithy-swift/blob/cb478655c8bdfe386d25f8b6729b3c9546c52742/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/CodegenVisitor.kt#L86-L93)
This preprocessing is not performed in tests.

**Comment by ganeshnj** [comment]
we must cleanup SetupTest methods which are duplicated all across.
- https://github.com/awslabs/smithy-swift/blob/cb478655c8bdfe386d25f8b6729b3c9546c52742/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/CodegenVisitor.kt#L175

**Comment by sichanyoo** [comment]
Re: codegen flow for codegen tests; left most unchanged because each test tests for specific portion of codegen, and setup varies wildly depending on tests. Still did refactor out `setUpTests` function for XML codegen tests bc those are exact duplicates.

Organized codegen test files physically using directories, and logically using Kotlin package declarations.
